# Generated by Django 5.1.15 on 2026-05-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisorderRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disorder', models.CharField(choices=[('normal', 'Normal'), ('anxiety', 'Anxiety'), ('depression', 'Depression'), ('stress', 'Stress'), ('bipolar', 'Bipolar'), ('suicidal', 'Suicidal'), ('personality', 'Personality Disorder')], max_length=20)),
                ('brainwave', models.CharField(choices=[('delta', 'Delta (0.5-4 Hz)'), ('theta', 'Theta (4-8 Hz)'), ('alpha', 'Alpha (8-13 Hz)'), ('beta', 'Beta (13-30 Hz)'), ('gamma', 'Gamma (30-100 Hz)')], max_length=10)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Lower = higher priority (1 = primary)')),
                ('target_frequency_hz', models.FloatField(help_text='Specific frequency to generate (within the brainwave band)')),
                ('carrier_frequency_hz', models.FloatField(default=200.0, help_text='Base carrier tone for binaural beats')),
                ('rationale', models.TextField(blank=True, help_text='Why this brainwave is recommended (shown to user)')),
            ],
            options={
                'ordering': ['disorder', 'priority'],
                'unique_together': {('disorder', 'brainwave')},
            },
        ),
    ]
