# Generated by Django 5.1.15 on 2026-04-12 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.DateTimeField()),
                ('wake_up_time', models.DateTimeField()),
                ('calculated_sleep_duration', models.DurationField(editable=False)),
                ('satisfaction_of_sleep', models.BooleanField()),
                ('late_night_sleep', models.BooleanField(default=False)),
                ('wake_up_frequently', models.BooleanField(default=False)),
                ('sleep_at_daytime', models.BooleanField(default=False)),
                ('drowsiness_tiredness', models.BooleanField(default=False)),
                ('recent_psychological_attack', models.BooleanField(default=False)),
                ('afraid_of_sleeping', models.BooleanField(default=False)),
                ('duration_of_problems', models.PositiveSmallIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
