# Generated by Django 5.1.15 on 2026-05-02 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sleeplog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyWellnessAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analysis_date", models.DateField(default=django.utils.timezone.localdate)),
                ("result", models.JSONField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("sleep_log", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wellness_snapshots", to="sleeplog.sleeplog")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_wellness_analyses", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-analysis_date", "-created_at"],
                "unique_together": {("user", "analysis_date")},
            },
        ),
    ]
