# Generated by Django 5.1.15 on 2026-04-22 13:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='The day this entry refers to.')),
                ('WorkoutTime', models.FloatField(help_text='Hours of workout today (0–3).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('ReadingTime', models.FloatField(help_text='Hours of reading today (0–2).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('PhoneTime', models.FloatField(help_text='Hours of phone use today (1–5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('WorkHours', models.FloatField(help_text='Hours worked today (4–10).', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)])),
                ('CaffeineIntake', models.PositiveIntegerField(help_text='Caffeine intake in mg (0–300).', validators=[django.core.validators.MaxValueValidator(300)])),
                ('RelaxationTime', models.FloatField(help_text='Hours of relaxation today (0–2).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('Work_x_Caffeine', models.FloatField(editable=False)),
                ('Screen_Time_Intensity', models.FloatField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='lifestyle_l_user_id_0dbc9b_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
