# Generated by Django 5.1.15 on 2026-04-30 15:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lifestyle', '0001_initial'),
        ('sleeplog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('journal_text', models.TextField(blank=True, default='')),
                ('model_outputs', models.JSONField(blank=True, null=True)),
                ('unified_profile', models.JSONField(blank=True, null=True)),
                ('reasoning_report', models.JSONField(blank=True, null=True)),
                ('final_output', models.JSONField(blank=True, null=True)),
                ('pipeline_metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for inputs'), ('MODELS_RUNNING', 'Models running'), ('MODELS_DONE', 'Models complete'), ('AGENT1_DONE', 'Correlation agent done'), ('AGENT2_DONE', 'Reasoning agent done'), ('AGENT3_DONE', 'Recommendation agent done'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='WAITING', max_length=24)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lifestyle_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lifestyle.lifestylelog')),
                ('sleep_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sleeplog.sleeplog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily progress',
                'verbose_name_plural': 'Daily progress',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='ai_dailypro_user_id_2667ad_idx'), models.Index(fields=['status'], name='ai_dailypro_status_e8f58a_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
